#!/bin/bash

#default value
branch=trunk
rev=HEAD
recovery=0
list=0
generic=1

#parse command line
while [ $# -gt 0 ]; do
  case $1  in
    -a)
      arch=$2
      shift 2
    ;;
    -r)
      rev=$2
      shift 2
    ;;
    -b)
      branch=$2
      shift 2
    ;;
    -g)
      generic=0
      shift 1
    ;;
    -l)
      list=1
      shift 1
    ;;
    -R)
      recovery=1
      shift 1
    ;;
    *)
      cat README
      exit 0	      
    ;;
  esac
done

#checkout svn
if [ ! -d ./svn/$branch ]; then
	mkdir -p svn
	case $branch in
	   trunk)
		repo=svn://svn.openwrt.org/openwrt/trunk/
		;;
	   backfire)
		repo=svn://svn.openwrt.org/openwrt/branches/backfire
		;;
	   kamikaze)
		repo=svn co svn://svn.openwrt.org/openwrt/branches/8.09
		;;
	   *)
		echo Unsupported $branch 
		exit 0
		;;
	esac
	svn co $repo ./svn/$branch
fi

#parse kernel version
#cd ./svn/$branch || exit0
kernel=`grep -o 'LINUX_VERSION:=[0-9.]*' ./svn/$branch/target/linux/$arch/Makefile | grep -o '[0-9.]*' $kernel`

mkdir -p kernels
if [ ! -f kernels/linux-$kernel.ori.tar.bz2]; then
	wget -c ftp://ftp.kernel.org/pub/linux/kernel/v2.6/linux-$kernel.tar.bz2 -O kernels/linux-$kernel.ori.tar.bz2
fi

mkdir -p kernels/linux-$kernel.ori
tar xvjf kernels/linux-$kernel.ori.tar.bz2 -C kernels/



